
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/15.0.3\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/15.0.3\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/mommywish.unaux.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=6.7.2"}};
/*! This file is auto-generated */
!function(i,n){var o,s,e;function c(e){try{var t={supportTests:e,timestamp:(new Date).valueOf()};sessionStorage.setItem(o,JSON.stringify(t))}catch(e){}}function p(e,t,n){e.clearRect(0,0,e.canvas.width,e.canvas.height),e.fillText(t,0,0);var t=new Uint32Array(e.getImageData(0,0,e.canvas.width,e.canvas.height).data),r=(e.clearRect(0,0,e.canvas.width,e.canvas.height),e.fillText(n,0,0),new Uint32Array(e.getImageData(0,0,e.canvas.width,e.canvas.height).data));return t.every(function(e,t){return e===r[t]})}function u(e,t,n){switch(t){case"flag":return n(e,"\ud83c\udff3\ufe0f\u200d\u26a7\ufe0f","\ud83c\udff3\ufe0f\u200b\u26a7\ufe0f")?!1:!n(e,"\ud83c\uddfa\ud83c\uddf3","\ud83c\uddfa\u200b\ud83c\uddf3")&&!n(e,"\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc65\udb40\udc6e\udb40\udc67\udb40\udc7f","\ud83c\udff4\u200b\udb40\udc67\u200b\udb40\udc62\u200b\udb40\udc65\u200b\udb40\udc6e\u200b\udb40\udc67\u200b\udb40\udc7f");case"emoji":return!n(e,"\ud83d\udc26\u200d\u2b1b","\ud83d\udc26\u200b\u2b1b")}return!1}function f(e,t,n){var r="undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?new OffscreenCanvas(300,150):i.createElement("canvas"),a=r.getContext("2d",{willReadFrequently:!0}),o=(a.textBaseline="top",a.font="600 32px Arial",{});return e.forEach(function(e){o[e]=t(a,e,n)}),o}function t(e){var t=i.createElement("script");t.src=e,t.defer=!0,i.head.appendChild(t)}"undefined"!=typeof Promise&&(o="wpEmojiSettingsSupports",s=["flag","emoji"],n.supports={everything:!0,everythingExceptFlag:!0},e=new Promise(function(e){i.addEventListener("DOMContentLoaded",e,{once:!0})}),new Promise(function(t){var n=function(){try{var e=JSON.parse(sessionStorage.getItem(o));if("object"==typeof e&&"number"==typeof e.timestamp&&(new Date).valueOf()<e.timestamp+604800&&"object"==typeof e.supportTests)return e.supportTests}catch(e){}return null}();if(!n){if("undefined"!=typeof Worker&&"undefined"!=typeof OffscreenCanvas&&"undefined"!=typeof URL&&URL.createObjectURL&&"undefined"!=typeof Blob)try{var e="postMessage("+f.toString()+"("+[JSON.stringify(s),u.toString(),p.toString()].join(",")+"));",r=new Blob([e],{type:"text/javascript"}),a=new Worker(URL.createObjectURL(r),{name:"wpTestEmojiSupports"});return void(a.onmessage=function(e){c(n=e.data),a.terminate(),t(n)})}catch(e){}c(n=f(s,u,p))}t(n)}).then(function(e){for(var t in e)n.supports[t]=e[t],n.supports.everything=n.supports.everything&&n.supports[t],"flag"!==t&&(n.supports.everythingExceptFlag=n.supports.everythingExceptFlag&&n.supports[t]);n.supports.everythingExceptFlag=n.supports.everythingExceptFlag&&!n.supports.flag,n.DOMReady=!1,n.readyCallback=function(){n.DOMReady=!0}}).then(function(){return e}).then(function(){var e;n.supports.everything||(n.readyCallback(),(e=n.source||{}).concatemoji?t(e.concatemoji):e.wpemoji&&e.twemoji&&(t(e.twemoji),t(e.wpemoji)))}))}((window,document),window._wpemojiSettings);


window.SureCartAffiliatesConfig = {
				"publicToken": "pt_Vy5Yj2MRxufCErmS3tgMn2g2",
				"baseURL":"https://api.surecart.com/v1"
			};


{"imports":{"@surecart\/checkout":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/packages\/blocks-next\/build\/scripts\/checkout\/index.js?ver=a3bd0720bee23cd51f06","@surecart\/checkout-events":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/packages\/blocks-next\/build\/scripts\/checkout-events\/index.js?ver=ed9647bd6c7865efe2ad","@wordpress\/interactivity":"http:\/\/mommywish.unaux.com\/wp-includes\/js\/dist\/script-modules\/interactivity\/index.min.js?ver=907ea3b2f317a78b7b9b","@surecart\/checkout-service":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/packages\/blocks-next\/build\/scripts\/checkout-actions\/index.js?ver=e76ded354be464e67eaa","@surecart\/google-events":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/packages\/blocks-next\/build\/scripts\/google\/index.js?ver=d92e383a18bcf54ea538","@surecart\/facebook-events":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/packages\/blocks-next\/build\/scripts\/facebook\/index.js?ver=cf5c6499cb7b867894c1","@surecart\/a11y":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/packages\/blocks-next\/build\/scripts\/a11y\/index.js?ver=fbe783039308da940df7","@surecart\/api-fetch":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/packages\/blocks-next\/build\/scripts\/fetch\/index.js?ver=1bfba8ea0694a193022a"}}


					window.scFetchData =
					{"root_url":"http:\/\/mommywish.unaux.com\/wp-json\/","nonce":"c498a45eb5","nonce_endpoint":"http:\/\/mommywish.unaux.com\/wp-admin\/admin-ajax.php?action=sc-rest-nonce"}				

var astra = {"break_point":"921","isRtl":"","is_scroll_to_id":"1","is_scroll_to_top":"1","is_header_footer_builder_active":"1","responsive_cart_click":"flyout","palette_key":""};


wp.i18n.setLocaleData( { 'text direction\u0004ltr': [ 'ltr' ] } );


var prestoComponents = {"url":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/presto-player\/dist\/components\/web-components\/web-components.esm.js?ver=1741173581"};
var prestoPlayer = {"plugin_url":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/presto-player\/","logged_in":"","root":"http:\/\/mommywish.unaux.com\/wp-json\/","nonce":"c498a45eb5","ajaxurl":"http:\/\/mommywish.unaux.com\/wp-admin\/admin-ajax.php","isAdmin":"","isSetup":{"bunny":false},"proVersion":"","isPremium":"","wpVersionString":"wp\/v2\/","prestoVersionString":"presto-player\/v1\/","debug":"","debug_navigator":"","i18n":{"skip":"Skip","rewatch":"Rewatch","emailPlaceholder":"Email address","emailDefaultHeadline":"Enter your email to play this episode.","chapters":"Chapters","show_chapters":"Show Chapters","hide_chapters":"Hide Chapters","restart":"Restart","rewind":"Rewind {seektime}s","play":"Play","pause":"Pause","fastForward":"Forward {seektime}s","seek":"Seek","seekLabel":"{currentTime} of {duration}","played":"Played","buffered":"Buffered","currentTime":"Current time","duration":"Duration","volume":"Volume","mute":"Mute","unmute":"Unmute","enableCaptions":"Enable captions","disableCaptions":"Disable captions","download":"Download","enterFullscreen":"Enter fullscreen","exitFullscreen":"Exit fullscreen","frameTitle":"Player for {title}","captions":"Captions","settings":"Settings","pip":"PIP","menuBack":"Go back to previous menu","speed":"Speed","normal":"Normal","quality":"Quality","loop":"Loop","start":"Start","end":"End","all":"All","reset":"Reset","disabled":"Disabled","enabled":"Enabled","advertisement":"Ad","qualityBadge":{"2160":"4K","1440":"HD","1080":"HD","720":"HD","576":"SD","480":"SD"},"auto":"AUTO","upNext":"Up Next","startOver":"Start Over"}};
var prestoComponents = {"url":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/presto-player\/dist\/components\/web-components\/web-components.esm.js?ver=1741173581"};
var prestoPlayer = {"plugin_url":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/presto-player\/","logged_in":"","root":"http:\/\/mommywish.unaux.com\/wp-json\/","nonce":"c498a45eb5","ajaxurl":"http:\/\/mommywish.unaux.com\/wp-admin\/admin-ajax.php","isAdmin":"","isSetup":{"bunny":false},"proVersion":"","isPremium":"","wpVersionString":"wp\/v2\/","prestoVersionString":"presto-player\/v1\/","debug":"","debug_navigator":"","i18n":{"skip":"Skip","rewatch":"Rewatch","emailPlaceholder":"Email address","emailDefaultHeadline":"Enter your email to play this episode.","chapters":"Chapters","show_chapters":"Show Chapters","hide_chapters":"Hide Chapters","restart":"Restart","rewind":"Rewind {seektime}s","play":"Play","pause":"Pause","fastForward":"Forward {seektime}s","seek":"Seek","seekLabel":"{currentTime} of {duration}","played":"Played","buffered":"Buffered","currentTime":"Current time","duration":"Duration","volume":"Volume","mute":"Mute","unmute":"Unmute","enableCaptions":"Enable captions","disableCaptions":"Disable captions","download":"Download","enterFullscreen":"Enter fullscreen","exitFullscreen":"Exit fullscreen","frameTitle":"Player for {title}","captions":"Captions","settings":"Settings","pip":"PIP","menuBack":"Go back to previous menu","speed":"Speed","normal":"Normal","quality":"Quality","loop":"Loop","start":"Start","end":"End","all":"All","reset":"Reset","disabled":"Disabled","enabled":"Enabled","advertisement":"Ad","qualityBadge":{"2160":"4K","1440":"HD","1080":"HD","720":"HD","576":"SD","480":"SD"},"auto":"AUTO","upNext":"Up Next","startOver":"Start Over"}};


var surecartComponents = {"url":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/dist\/components\/surecart\/surecart.esm.js?ver=1742365284"};
var scData = {"cdn_root":"https:\/\/surecart.com\/cdn-cgi\/image","root_url":"http:\/\/mommywish.unaux.com\/wp-json\/","plugin_url":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart","home_url":"http:\/\/mommywish.unaux.com","api_url":"https:\/\/api.surecart.com\/v1\/","currency":"inr","currency_symbol":"\u20b9","theme":"light","pages":{"dashboard":"http:\/\/mommywish.unaux.com\/customer-dashboard\/","checkout":"http:\/\/mommywish.unaux.com\/checkout\/"},"page_id":"","nonce":"c498a45eb5","nonce_endpoint":"http:\/\/mommywish.unaux.com\/wp-admin\/admin-ajax.php?action=sc-rest-nonce","recaptcha_site_key":"","claim_url":"","admin_url":"http:\/\/mommywish.unaux.com\/wp-admin\/","getting_started_url":"http:\/\/mommywish.unaux.com\/wp-admin\/admin.php?page=sc-getting-started","user_permissions":{"manage_sc_shop_settings":false},"is_account_connected":"1"};
var scIcons = {"path":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/dist\/icon-assets"};
var surecartComponents = {"url":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/dist\/components\/surecart\/surecart.esm.js?ver=1742365284"};
var scData = {"cdn_root":"https:\/\/surecart.com\/cdn-cgi\/image","root_url":"http:\/\/mommywish.unaux.com\/wp-json\/","plugin_url":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart","home_url":"http:\/\/mommywish.unaux.com","api_url":"https:\/\/api.surecart.com\/v1\/","currency":"inr","currency_symbol":"\u20b9","theme":"light","pages":{"dashboard":"http:\/\/mommywish.unaux.com\/customer-dashboard\/","checkout":"http:\/\/mommywish.unaux.com\/checkout\/"},"page_id":"259","nonce":"c498a45eb5","nonce_endpoint":"http:\/\/mommywish.unaux.com\/wp-admin\/admin-ajax.php?action=sc-rest-nonce","recaptcha_site_key":"","claim_url":"","admin_url":"http:\/\/mommywish.unaux.com\/wp-admin\/","getting_started_url":"http:\/\/mommywish.unaux.com\/wp-admin\/admin.php?page=sc-getting-started","user_permissions":{"manage_sc_shop_settings":false},"is_account_connected":"1"};
var scIcons = {"path":"http:\/\/mommywish.unaux.com\/wp-content\/plugins\/surecart\/dist\/icon-assets"};


var st_ajax_object = {"ajax_url":"http:\/\/mommywish.unaux.com\/wp-admin\/admin-ajax.php"};


var starter_templates_zip_preview = {"AstColorPaletteVarPrefix":"--ast-global-color-","AstEleColorPaletteVarPrefix":["ast-global-color-0","ast-global-color-1","ast-global-color-2","ast-global-color-3","ast-global-color-4","ast-global-color-5","ast-global-color-6","ast-global-color-7","ast-global-color-8"]};


			/(trident|msie)/i.test(navigator.userAgent)&&document.getElementById&&window.addEventListener&&window.addEventListener("hashchange",function(){var t,e=location.hash.substring(1);/^[A-z0-9_-]+$/.test(e)&&(t=document.getElementById(e))&&(/^(?:a|select|input|button|textarea)$/i.test(t.tagName)||(t.tabIndex=-1),t.focus())},!1);
			